# Secton 3

Import numpy for use in this notebook. \
Run the first cell to import numpy and check the version.


In [1]:
import numpy as np

print(np.__version__)

1.24.2


# Section 4 (Exercises 1-10)

### Exercise 1

In [3]:
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

D = np.array([0.1, 0.3])

#Solution 1
print("A: ", np.all(A))
print("B: ", np.all(B))
print("C: ", np.all(C))
print("D: ", np.all(D))

# Solution 2
for name, array in zip(list('ABCD'), [A, B, C, D]):
    print(f'{name}: {np.all(array)}')


A:  True
B:  False
C:  False
D:  True


### Exercise 2
Check if all elements from the following arrays return the logical value True along the axis with index 1

```python
{
    A = np.array([[3, 2, 1, 4],
                [5, 2, 1, 6]])

    B = np.array([[3, 2, 1, 4],
                [5, 2, 0, 6]])

    C = np.array([[True, False, False],
                [True, True, True]])
}
```

Print result to the console as shown below.

Tip: Use the function `np.all()` with the axis argument.

Expected result:

```python
{
    A: [ True  True]
    B: [ True False]
    C: [False  True]
}
```


In [6]:
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

#solution
for name, array in zip(list('ABC'), [A, B, C]):
    print(f'{name}: {np.all(array, axis=1)}')


A: [ True  True]
B: [ True False]
C: [False  True]


### Exercise 3

Check if any element of the following arrays returns the logical value `True`:

```python
{
    A = np.array([[0, 0, 0],
              [0, 0, 0]])

    B = np.array([[0, 0, 0],
                [0, 1, 0]])

    C = np.array([[False, False, False],
                [True, False, False]])

    D = np.array([[0.1, 0.0]])
}
```

Print result to the console as shown below.

Tip: Use the `np.any()` function.

Expected result:

```python
{
    A: False
    B: True
    C: True
    D: True
}
```


In [14]:
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

#Solution
for name, array in zip(list('ABCD'), [A, B, C, D]):
    print(f'{name}: {np.any(array)}')

A: False
B: True
C: True
D: True


## Exercise 4

Check if any element of the following arrays returns the logical value True along the axis with index 0:

```python
{
    A = np.array([[0, 0, 0],
                 [0, 0, 0]])

    B = np.array([[0, 0, 0],
                [0, 1, 0]])

    C = np.array([[False, False, False],
                [True, False, False]])

    D = np.array([[0.1, 0.0]])
}
```

Print result to the console as shown below.

Tip: Use the `np.any()` function with the axis argument.

Expected result:

```python
{
    A: [False False False]
    B: [False  True False]
    C: [ True False False]
    D: [ True False]
}
```


In [11]:
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

#Solution
for name, array in zip(list('ABCD'), [A, B, C, D]):
    print(f'{name}: {np.any(array, axis=0)}')

A: [False False False]
B: [False  True False]
C: [ True False False]
D: [ True False]


### Exercise 5

Check if the following array has missing data (np.nan):

```python showLineNumbers
{
    A = np.array([[3, 2, 1, np.nan],
                [5, np.nan, 1, 6]])
}
```

Print result to the console as shown below.

Tip: Use the `np.isnan()` function.

Expected result:

```python
{
    [[False False False  True],
    [False  True  False  False]]
 }
```


In [15]:
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])

# Solution
np.isnan(A)

array([[False, False, False,  True],
       [False,  True, False, False]])

Exercise 6
Check if the following arrays are equal (element-wise):

```python
{
    A = np.array([0.4, 0.5, 0.3])
    B = np.array([0.39999999, 0.5000001, 0.3])
}
```

Use the `np.allclose()` function with default parameters and print result to the console.

Expected result:

```python
    True
```


In [17]:
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])

np.allclose(A, B)


True

### Exercise 7

Check if the following arrays are equal (element-wise):

```python
{
    A = np.array([0.4, 0.5, 0.3])
    B = np.array([0.3999999999, 0.5000000001, 0.3])
}
```

Use the comparison operator `==` in this exercise and print the result to the console.

Expected result:

```python
    [False False  True]
```


In [19]:
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.3999999999, 0.5000000001, 0.3])

print(A == B)


[False False  True]


### Exercise 8

The following arrays are given:

```python
{
    A = np.array([0.4, 0.5, 0.3, 0.9])
    B = np.array([0.38, 0.51, 0.3, 0.91])
}
```

Check which numbers (element-wise) from the **A** array are greater than numbers from the **B** array and print result to the console as shown below.

Expected result:

```python
[ True False False False]
```


In [20]:
A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])

print(A > B)

[ True False False False]


### Exercise 9

Using *Numpy* create a **4x4 array filled with zeros** (set data type to int). In response print this array to the console.

Tip: Use the `np.zeros()` function.

Expected result:

```
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
```


In [28]:
# Solution
zeros=np.zeros(shape=(4, 4), dtype=int)

print(zeros)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


### Exercise 10

Using _Numpy_, create an array 10x10 filled with number 255 and set the data type to float. Print this array to the console as shown below.

Tip: Use the `np.ones()` or `np.full()` functions.

Expected result:

```python
[[255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]]
```


In [32]:
# Solution 1
print(np.ones(shape=(10, 10), dtype='float') * 255)

# Solution 2

# numpy.full(shape, fill_value, dtype=None, order='C', *, like=None)

mat=np.full(shape=(10, 10), fill_value=255, dtype='float')
print(mat)

[[255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]]


# Setion 5: Excersises 11-20

### Exercise 11

Using _Numpy_ create a one-dimensional array of all two-digit numbers and print this array to the console as shown below.

Tip: Use the `np.arange()` function.

Expected result:

```python
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
```


In [38]:
print(np.arange(10, 100, 1))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


### Exercise 12

Using _Numpy_ create the following array:

```python
    [[10 11 12 13 14 15 16 17 18 19]
    [20 21 22 23 24 25 26 27 28 29]
    [30 31 32 33 34 35 36 37 38 39]
    [40 41 42 43 44 45 46 47 48 49]
    [50 51 52 53 54 55 56 57 58 59]
    [60 61 62 63 64 65 66 67 68 69]
    [70 71 72 73 74 75 76 77 78 79]
    [80 81 82 83 84 85 86 87 88 89]
    [90 91 92 93 94 95 96 97 98 99]]
```

Note that the shape of this array is (9, 10). In response, print array to the console.

**Tip:** Use the `np.arange()` function and the `np.ndarray.reshape()` method.
